templateStatePooh:templateStatePooh.o 
	g++ -o templateStatePooh templateStatePooh.o 


templateStatePooh.o:templateStatePooh.cpp
	g++ -c templateStatePooh.cpp
	
	
clean:
	rm *.o
	rm templateStatePooh

